//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
namespace Payroll
{
	class PayrollDatabase
	{
		private static Hashtable employees = new Hashtable();
        private static Hashtable unionMembers = new Hashtable();

		public static void AddEmployee(int id, Employee employee)
		{
			employees.Add(id, employee);
		}

		public static Employee GetEmployee(int id)
		{
			return employees[id] as Employee;
		}

		public static void DeleteEmployee(int id)
		{
			if (employees.ContainsKey(id))
			{
				employees.Remove(id);
			}
		}

        public static void AddUnionMember(int id, Employee employee)
        {
            unionMembers.Add(id, employee);
        }

        public static Employee GetUnionMember(int id)
        {
            if (unionMembers.ContainsKey(id))
            {
                return unionMembers[id] as Employee;
            }
            return null;
        }
	}
}

