//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
namespace Payroll
{
	class HourlyClassification : PaymentClassification
	{
		private Hashtable timeCards = new Hashtable();

		public HourlyClassification (float hour)
		{
			Hours = hour;
		}

		public float Hours
		{
			get; set;
		}

		public void AddTimeCard(TimeCard timeCard)
		{
			timeCards.Add(timeCard.Date.Day, timeCard);
		}

		public TimeCard GetTimeCard(DateTime date)
		{
			if (timeCards.Contains(date.Day))
			{
				return timeCards[date.Day] as TimeCard;
			}
			return null;
		}

        public override double CalculatePay(Paycheck paycheck)
        {
            throw new NotImplementedException();
        }
	}

}

