//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Payroll
{
	class TimeCard
	{
		private DateTime date;
		private float hours;

		public TimeCard (DateTime date, float hours)
		{
			this.date = date;
			this.hours = hours;
		}
		

		public DateTime Date {
			get {
				return this.date;
			}
		}

		public float Hours {
			get {
				return this.hours;
			}
	    }
	}


}

