//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using NUnit.Core;
using NUnit.Framework;
using Payroll;
namespace Payroll.Test
{
	class PayrollTestAddEmployee
	{
		private static Employee GetEmployee (int empid)
		{
			Employee e = PayrollDatabase.GetEmployee (empid);
			Assert.IsNotNull (e);
			return e;
		}

		public static Employee AddSalariedEmployee(int empid, string name, string address, double salary)
		{
			AddSalariedEmployee t = new AddSalariedEmployee(empid, name, address, salary);
			t.Execute();

			return GetEmployee (empid);

		}

		public static Employee AddHourlyEmployee(int empid, string name, string address, double hourlyRate)
		{
			AddHourlyEmployee t = new AddHourlyEmployee(empid, name, address, hourlyRate);
			t.Execute();
			
			return GetEmployee (empid);
			
		}

		public static Employee AddCommissiondEmployee(int empid, string name, string address, double salary, double percent)
		{
			AddCommissiondEmployee t = new AddCommissiondEmployee(empid, name, address, salary, percent);
			t.Execute();
			
			return GetEmployee (empid);
			
		}
	}
}

