//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using MySql.Data.MySqlClient;
namespace Payroll
{
	class RealPayrollDatabase : PayrollDatabase
	{
		private MySqlConnection connection;

		public RealPayrollDatabase()
		{
			MySql.Data.MySqlClient.MySqlConnection conn;
			string myConnectionString;
			
			/*myConnectionString = "server=104.224.133.206;uid=root;" +
				"pwd=root;database=test;pooling=true;";*/

			myConnectionString = "server=127.0.0.1;uid=root;" +
				"pwd=0903;database=payroll;pooling=true;";
			
			try
			{
				connection = new MySql.Data.MySqlClient.MySqlConnection();
				connection.ConnectionString = myConnectionString;
				connection.Open();
			}
			catch (MySql.Data.MySqlClient.MySqlException ex)
			{
				Console.WriteLine(ex.Number + " " + ex.Message);
			}
		}

		public void AddEmployee (int id, Employee employee)
		{
			string addCommand = "insert into Employee values (@EmpId, @Name, @Address)";
			MySqlCommand command = new MySqlCommand(addCommand, connection);

			command.Prepare();
			command.Parameters.AddWithValue("@EmpId", employee.EmpId);
			command.Parameters.AddWithValue("@Name", employee.Name);
			command.Parameters.AddWithValue("@Address", employee.Address);

			command.ExecuteNonQuery();
			//command.Parameters.AddWithValue("@Address", employee.Address);


		}

		public Employee GetEmployee (int id)
		{
			throw new NotImplementedException ();
		}

		public System.Collections.ArrayList GetAllEmployeeIds ()
		{
			throw new NotImplementedException ();
		}

		public void DeleteEmployee (int id)
		{
			throw new NotImplementedException ();
		}

		public void AddUnionMember (int id, Employee employee)
		{
			throw new NotImplementedException ();
		}

		public Employee GetUnionMember (int id)
		{
			throw new NotImplementedException ();
		}

		public void RemoveUnionMember (int memberId)
		{
			throw new NotImplementedException ();
		}
	}
}

