//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using NUnit.Core;

namespace Payroll
{
	abstract class AddEmployeeTransaction : Transaction
	{
		private readonly int empid;
		private readonly string name;
		private readonly string address;

		public AddEmployeeTransaction (int empid, string name, string address)
		{
			this.empid = empid;
			this.name = name;
			this.address = address;
		}

		protected abstract PaymentClassification MakeClassification();

		protected abstract PaymentSchedule MakeSchedule();

		public void Execute()
		{
			PaymentClassification pc = MakeClassification();
			PaymentSchedule ps = MakeSchedule();
			PaymentMethod pm = new HoldMethod();

			Employee e = new Employee(empid, name, address);
			e.Classification = pc;
			e.Schedule = ps;
			e.Method = pm;

			PayrollDatabase.AddEmployee(empid, e);
		}
	}

}

