//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Payroll
{
	class SalesReceipt
	{
		private DateTime saleDate;
		private double saleAmount;

		public SalesReceipt (DateTime saleDate, double saleAmount)
		{
			this.saleDate = saleDate;
			this.saleAmount = saleAmount;
		}

		public DateTime SaleDate {
			get {
				return saleDate;
			}
		}

		public double SaleAmount {
			get {
				return saleAmount;
			}
		}
	}

}

