//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Payroll
{
	class BiweeklySchedule : PaymentSchedule
	{
		public BiweeklySchedule ()
		{
		}

        public override bool IsPayDate(DateTime payDate)
        {
            throw new NotImplementedException();
        }

        private bool IsWeeklyDate(DateTime date)
        {
            return false;
        }
	}
}

